#Сборка
name: My-Otus-lesson-ci
env:
  DEPLOY_PACKAGE : "flask_app_${{ github.sha}}.zip"
on : 
  push :
    branches : 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: echo Hello, word!
  
