#Сборка
name: My-Otus-lesson-ci
on : 
  push :
    branches : 
      - main

jobs:
  build:
    runs-on: alpine
    steps:
    - uses: action:/checkout@v1
    - name: Run
      run: echo Hello, word!
  
