#Сборка
name: My-Otus-lesson-ci
on : 
  push :
    branches : 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/otus:latest
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run docker container
        run: docker run -d -p 5000:5000 --name otus cl1ven/otus:latest
      - name: test port
        run: docker port otus 5000/tcp
      - name: destroy docker container
        run: docker rm -f otus
